import pytest


@pytest.fixture
def vacancy_112238167():
    return [
        {
            "id": "112238167",
            "premium": False,
            "name": "Оператор на выписку",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "95", "name": "Тюмень", "url": "https://api.hh.ru/areas/95"},
            "salary": {"from": 50000, "to": 55000, "currency": "RUR", "gross": False},
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Тюмень",
                "street": "Барабинская улица",
                "building": "3с14",
                "lat": 57.157242,
                "lng": 65.603795,
                "description": None,
                "raw": "Тюмень, Барабинская улица, 3с14",
                "metro": None,
                "metro_stations": [],
                "id": "17056739",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2024-11-30T17:59:15+0300",
            "created_at": "2024-11-30T17:59:15+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=112238167",
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/112238167?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/112238167",
            "relations": [],
            "employer": {
                "id": "11636603",
                "name": "Гермес",
                "url": "https://api.hh.ru/employers/11636603",
                "alternate_url": "https://hh.ru/employer/11636603",
                "logo_urls": None,
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=11636603",
                "accredited_it_employer": False,
                "trusted": False,
            },
            "snippet": {
                "requirement": "Знания 1С. Пунктуальность. Коммуникабельность. Стрессоустойчивость. Ответственность. Внимательность. Умение работать с кассой или терминалом (в крайнем случае сможем обучить).",
                "responsibility": "Работа с поступлениями и выпиской товара. С документами. С кассовыми документами. Клиентами.",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "professional_roles": [{"id": "40", "name": "Другое"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "noExperience", "name": "Нет опыта"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        }
    ]


@pytest.fixture
def vacancy_street():
    return [
        {
            "id": "112139788",
            "premium": False,
            "name": "Водитель автомобиля легкового",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "95", "name": "Тюмень", "url": "https://api.hh.ru/areas/95"},
            "salary": None,
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Тюмень",
                "street": "улица Пермякова",
                "building": "6",
                "lat": 57.132044,
                "lng": 65.596042,
                "description": None,
                "raw": "Тюмень, улица Пермякова, 6",
                "metro": None,
                "metro_stations": [],
                "id": "4868892",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2024-11-29T11:01:37+0300",
            "created_at": "2024-11-29T11:01:37+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=112139788",
            "show_logo_in_search": None,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/112139788?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/112139788",
            "relations": [],
            "employer": {
                "id": "2651823",
                "name": "ВГТРК (Всероссийская государственная телевизионная и радиовещательная компания)",
                "url": "https://api.hh.ru/employers/2651823",
                "alternate_url": "https://hh.ru/employer/2651823",
                "logo_urls": {
                    "original": "https://img.hhcdn.ru/employer-logo-original/521345.jpg",
                    "240": "https://img.hhcdn.ru/employer-logo/2526858.jpeg",
                    "90": "https://img.hhcdn.ru/employer-logo/2526857.jpeg",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=2651823",
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Водительское удостоверение категории В. Мед.осмотр. Пунктуальность, исполнительность.",
                "responsibility": "Управление служебным автомобилем. Доставка корреспондентов к месту событий по городу, также межгород. Заполнение путевых листов, отмечая маршруты следования. ",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "professional_roles": [{"id": "21", "name": "Водитель"}],
            "accept_incomplete_resumes": True,
            "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        }
    ]
